version: '3.9'

services:
  db:
    image: 'postgres:15'
    restart: always
    environment:
      POSTGRES_PASSWORD: handshake
      POSTGRES_USER: handshake
      POSTGRES_DB: handshake
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
